spring:
  application:
    name: AudioToText
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db/audio_to_text
    username: root
    password: example
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
security:
  cors:
    allowed-origin-patterns: "http://localhost:10881,http://localhost:5173"