audio:
  path:
    model-directory: ./model/your_model_name
    temp-file-directory: ./temp
spring:
  application:
    name: AudioToText
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: your_password
    url: jdbc:mysql://localhost:3306/your_db_name
    username: your_username
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB